"""Update ScheduledBlast.twilio_message_sid to Text

Revision ID: 1327fffbdc61
Revises: 
Create Date: 2024-10-19 04:10:41.723287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1327fffbdc61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_blast', schema=None) as batch_op:
        batch_op.alter_column('twilio_message_sid',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_blast', schema=None) as batch_op:
        batch_op.alter_column('twilio_message_sid',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=34),
               existing_nullable=True)

    # ### end Alembic commands ###
